export const ADD_SOURCE = 'ADD_SOURCE';
export const ADD_SOURCES = 'ADD_SOURCES';
export const SELECT_SOURCE = 'SELECT_SOURCE';
export const UNSELECT_SOURCE = 'UNSELECT_SOURCE';
export const CLEAR_SOURCES = 'CLEAR_SOURCES';
export const CLEAR_SELECTED_SOURCES = 'CLEAR_SELECTED_SOURCES';
export const GET_AVAILABLE_SOURCES = 'GET_AVAILABLE_SOURCES';
export const GET_AVAILABLE_SOURCES_FAILED = 'GET_AVAILABLE_SOURCES_FAILED';
